# Generated by Django 4.2.3 on 2024-06-08 17:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store_app", "0003_alter_product_image_tag_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Information",
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
