# Generated by Django 4.2.3 on 2024-06-11 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("store_app", "0005_contact_us"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=200)),
                ("lastname", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("postcode", models.IntegerField()),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=200)),
                ("additional_info", models.TextField()),
                ("amount", models.CharField(max_length=200)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Orderitem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prduct", models.CharField(max_length=200)),
                ("image", models.ImageField(upload_to="Product_images/Order_Img")),
                ("quantity", models.CharField(max_length=20)),
                ("price", models.CharField(max_length=50)),
                ("total", models.CharField(max_length=1000)),
                (
                    "Order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store_app.order",
                    ),
                ),
            ],
        ),
    ]
